######################################################################
# Automatically generated by qmake (2.01a) pon. kwi 9 21:10:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.hpp mem.hpp z80_cpu.hpp z80_proc.hpp
SOURCES += mem.cpp test.cpp z80_cpu.cpp
